### ISSUE TITLE
Length cannot be less than zero

### ISSUE THREAD

**Issue by lxalln** [spekt/junit.testlogger#11]
I am getting an exception when using this logger.
My tests are written in xUnit, my command looks like:

`dotnet test tests/UnitTests --logger:"junit;LogFilePath=..\UnitTests.xml;MethodFormat=Class;FailureBodyFormat=Verbose" --test-adapter-path:.`

I am getting the following error:

```
JunitXML Logger: Threw an unhandeled exception.
Length cannot be less than zero.
Parameter name: length
System.Private.CoreLib
```

![image](https://user-images.githubusercontent.com/2781908/65951523-1ef22d00-e438-11e9-990c-49974f6d42a5.png)

Is there a way I get more information that might actually be helpful?

Version: 2.1.10

**Comment by codito** [comment]
@lxalln thanks for reporting the issue. Can you run `dotnet test tests/UnitTests --logger:"junit;LogFilePath=..\UnitTests.xml;MethodFormat=Class;FailureBodyFormat=Verbose" --test-adapter-path:. --diag:log.txt` and share the `log*.txt` file.

Kindly review the `log*.txt` files to remove any secrets etc. before sharing.

**Comment by lxalln** [comment]
Before uploading the files (because they are large), here is where the exception is being thrown.

```
System.ArgumentOutOfRangeException: Length cannot be less than zero.
Parameter name: length
   at System.String.Substring(Int32 startIndex, Int32 length)
   at Microsoft.VisualStudio.TestPlatform.Extension.JUnit.Xml.TestLogger.JUnitXmlTestLogger.CreateTestCaseElement(TestResultInfo result)
   at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
   at System.Xml.Linq.XContainer.AddContentSkipNotify(Object content)
   at Microsoft.VisualStudio.TestPlatform.Extension.JUnit.Xml.TestLogger.JUnitXmlTestLogger.CreateTestSuiteElement(List`1 results)
   at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
   at System.Xml.Linq.XContainer.AddContentSkipNotify(Object content)
   at Microsoft.VisualStudio.TestPlatform.Extension.JUnit.Xml.TestLogger.JUnitXmlTestLogger.CreateTestSuitesElement(List`1 results)
   at Microsoft.VisualStudio.TestPlatform.Extension.JUnit.Xml.TestLogger.JUnitXmlTestLogger.TestRunCompleteHandler(Object sender, TestRunCompleteEventArgs e)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at Microsoft.VisualStudio.TestPlatform.Utilities.MulticastDelegateUtilities.SafeInvoke(Delegate delegates, Object sender, EventArgs args, String traceDisplayName)
```

I have taken a look in the `CreateTestCaseElement` method, and don't see any calls to `String.Substring`

Happy to upload the files if they will add context.

**Comment by codito** [comment]
Is it possible to share FullyQualifiedName of test method? ~Which test framework are you using?~ I see you mentioned xUnit above.

**Comment by lxalln** [comment]
I'm using nested classes, which do produce a 'different' FQN:

Example: `UnitTests.Domain.Orders.Checkout.CreateCheckoutOrderTests+TheHandler.RebuildsManifestIfAnyPromotionHasLimitedUse`

Note the `+` where the nested class is output.

**Comment by codito** [comment]
The issue repros with any xUnit test. I tried with `dotnet new xunit`.

Unfortunately the information provided by xUnit and NUnit adapters are different. This logger understands NUnit outputs. We may need to add support for xUnit.

**Comment by codito** [comment]
As a workaround please consider https://github.com/spekt/xunit.testlogger with https://github.com/gabrielweyer/xunit-to-junit

**Comment by lxalln** [comment]
That makes sense then. I didn't see any mention of xUnit restrictions, but that's probably because I didn't read far enough.

I'll take a look at the workaround.

**Comment by Siphonophora** [comment]
@lxalln Thanks again for reporting this. This project was just released so I appreciate you taking a look. I looked into it and believe this is resolved in the [current pre-release package](https://www.myget.org/feed/spekt/package/nuget/JunitXml.TestLogger). What I was able to confirm was that the pre-release does work without issue for the 'dotnet new xunit' project, and the FQN you provided above should be parsed just fine. If you are able to try the pre-release that would be great. 

@codito The substring call that error-ed was a DRY violation, so I had changed it in #10 to use the output of the improved parser.

**Comment by codito** [comment]
@Siphonophora awesome, thanks for debugging. Will wait for @lxalln to confirm and we can push the pre-release to nuget.

The differences in xunit and nunit adapters mentioned above are special outputs like [this](https://github.com/spekt/xunit.testlogger/blob/master/src/Xunit.Xml.TestLogger/XunitXmlTestLogger.cs#L279). I think we should create an abstraction to handle these adapter specific nuances. This library should also provide common args parsing like LogFilePath etc. in addition to utilities like TestCaseNameParser which can be reused across.

**Comment by codito** [comment]
Created https://github.com/spekt/testlogger for the common library.

**Comment by lxalln** [comment]
@Siphonophora @codito I have tried using the pre-release package, and it works correctly! Thanks.

Also to note, the workaround worked too. 

I'll wait for this to hit nuget, then will change over. Thanks for the quick turn-around guys :)

**Comment by codito** [comment]
@lxalln thank you for confirmation. Pushed to nuget: https://www.nuget.org/packages/JunitXml.TestLogger/2.1.15
