### ISSUE TITLE
No test logging was found with AssemblyQualifiedName, URI, or FriendlyName "junit".

### ISSUE THREAD

**Issue by boexler** [spekt/junit.testlogger#14]
I always get the following error:

`dotnet test --no-build -c Release -v n myProject.test.csproj --test-adapter-path:. --logger:"junit;LogFilePath=foo.xml"`

> No test logging was found with AssemblyQualifiedName, URI, or FriendlyName "junit".

Can anybody give me a hint whats wrong?

**Comment by Siphonophora** [comment]
@dojo90 Sure thing. One item to confirm is that you have the nuget package Microsoft.NET.Test.Sdk installed. Assuming you do, I would guess the logger isn't being copied into the release folder. I have seen some variation between .Net core / framework in this respect. What type of project are you testing?

**Comment by boexler** [comment]
After complete cleanup of solution/build server and reinstalling of the nuget package. Everything is now working as expected. I cannot reproduce the error. So don't know what was wrong..

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.2</TargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DeepEqual" Version="2.0.0" />
    <PackageReference Include="JunitXml.TestLogger" Version="2.1.15" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.4.0" />
    <PackageReference Include="xunit" Version="2.4.1" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.4.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="JunitXml.TestLogger" Version="2.1.15" />
  </ItemGroup>
</Project>
```
