### ISSUE TITLE
time field is rendered incorrectly.

### ISSUE THREAD

**Issue by AnashOommen** [spekt/junit.testlogger#16]
The ```time``` field is rendered as a ```float```, whereas it should be an ```xs:decimal``` per the JUnit schema. I have, for instance, a test that gets rendered like this:

```
<testcase classname="****" name="TestPartialFailureLogs" file="***.dll" time="1E-07" />
```
See the schema for more details.

https://github.com/windyroad/JUnit-Schema/blob/master/JUnit.xsd#L128

**Comment by Siphonophora** [comment]
Resolved: https://github.com/spekt/junit.testlogger/releases/tag/v2.1.32
