### ISSUE TITLE
timestamp field is rendered incorrectly

### ISSUE THREAD

**Issue by AnashOommen** [spekt/junit.testlogger#17]
The timestamp field is rendered like this: 

```timestamp="2020-01-24T 01:21:18Z"```

whereas it should be like this:
```2008-01-24T01:21:18```

See the schema for more details.

https://github.com/windyroad/JUnit-Schema/blob/master/JUnit.xsd#L13

Rendering the timestamp like 

```DateTime.UtcNow.ToString("s")```

Should give this formatting.

**Comment by Siphonophora** [comment]
Resolved: https://github.com/spekt/junit.testlogger/releases/tag/v2.1.32
