### ISSUE TITLE
Save the XML without BOM mark

### ISSUE THREAD

**Issue by AnashOommen** [spekt/junit.testlogger#18]
Currently, the tool generates the xml as utf-8 encoded with BOM mark. Can we do the following?

1. Encode without a BOM mark. You can pass a ``UTFEncoding(false)`` to the ```XmlTextWriter``` constructor to achieve this.  https://stackoverflow.com/questions/4942825/xdocument-saving-xml-to-file-without-bom?answertab=votes#tab-top

2. Provide a flag to control this behaviour if this is a breaking change, so I can run this like:

```dotnet test --test-adapter-path:. --logger:"junit;LogFilePath=test-result.xml;SkipUtf8Bom=true" test.csproj```

**Comment by Siphonophora** [comment]
@AnashOommen Thanks for pointing this out. For this issue as well as #16 and #17 could you share what you are using to read the xml output? My testing of this library has focused on making sure GitLab is able to parse the files. Best I can tell, it doesn't actually care about the time or date, which may be why this hasn't been an issue so far. I haven't had a chance to test directly with CircleCI or others. 

I think a flag would be better. I would be happy with this:
* FileEncoding=utf8bom  (default)
* FileEncoding=utf8

**Comment by AnashOommen** [comment]
I’m using this against an internal linux-based CI/CD system that expects JUnit-compatible xml output from the tests. I don’t know more details right now.

I strongly suspect it is validating the generated xml against the xsd I linked in one of the bugs, which is why it is failing in my case whereas passes in GitLab. utf-8 with bom encoding is typically the windows way of encoding files, parsers for timestamp for are more flexible than xsd validation, etc.

If it helps, I can upload an xml on Monday and you could validate it against the xsd I linked.

**Comment by Siphonophora** [comment]
@AnashOommen That make sense. An example wouldn't hurt if you have one.

**Comment by codito** [comment]
I'm wondering if we should make simple `utf-8` _without_ BOM the default format. Unicode spec doesn't recommend BOM. Is there a scenario which would break if we do this?

This stackoverflow question covers some pros/cons of utf-8 with/without BOM: https://stackoverflow.com/a/2223926

**Comment by Siphonophora** [comment]
For gitlab at least, standard UTF8 isn't a problem. It does seem likely its a safe standard option, I was just being conservative about changing the output.

That said, there was an issue in one of the other loggers requesting a changelog. Seems worth creating one just in case if we change it.

**Comment by codito** [comment]
+1 to Changelog. Let's provide BOM as an option if anyone would like the old behavior. Like previous releases, we can do a myget release and wait for a few days to see if anything breaks prior to nuget release.

**Comment by Siphonophora** [comment]
@AnashOommen We decided to switch to plain UTF-8 as the default. 

The new [pre-release package](https://www.myget.org/feed/spekt/package/nuget/JunitXml.TestLogger) includes a resolution for this issue, along with #16, #17. If you have time to take a look and provide feedback, that would be great.

**Comment by AnashOommen** [comment]
Sure, I'll try sometime this week.

**Comment by Siphonophora** [comment]
@AnashOommen did you ever get a chance to try this? Thanks

**Comment by Siphonophora** [comment]
Resolved: https://github.com/spekt/junit.testlogger/releases/tag/v2.1.32
