### ISSUE TITLE
Clarify the requirements for contributing to this project...

### ISSUE THREAD

**Issue by AnashOommen** [spekt/junit.testlogger#19]
Can someone add a CONTRIBUTING.md to this project to clarify how to contribute to this project? I can't tell for instance if I need to sign a CLA (I'm fairly sure it doesn't, but it's nice to know for reference of a reader.).

**Comment by Siphonophora** [comment]
@AnashOommen Hi, no you don't need to sign anything to contribute.

**Comment by codito** [comment]
https://github.com/spekt/testlogger?tab=readme-ov-file#contribution-guide
