### ISSUE TITLE
Transfer to spekt

### ISSUE THREAD

**Issue by codito** [spekt/junit.testlogger#2]
@Siphonophora deleted the fork, we can try transferring this repo to `spekt` now.

**Comment by Siphonophora** [comment]
@codito It just said I don't have the ability to create repos in spekt.

**Comment by codito** [comment]
oh, would you mind adding me as a collaborator to this repo?

**Comment by codito** [comment]
Invited you to join spekt, hopefully that would give you permissions to create repo.

**Comment by Siphonophora** [comment]
Added you as a collaborator, still can't create a repo in spekt

**Comment by Siphonophora** [comment]
@codito  Turns out I could request to transfer to you directly, even though I can't make it in spekt.

**Comment by Siphonophora** [comment]
Ok, actually accepting the invite fixed this.

**Comment by Siphonophora** [comment]
@codito  Looks like the last thing to do is setup my privileges and put back the topic links.

**Comment by codito** [comment]
@Siphonophora updated topics and added you as a maintainer for the repo.
