### ISSUE TITLE
warning about configuration 'TargetFramework'

### ISSUE THREAD

**Issue by moly** [spekt/junit.testlogger#31]
Every time I run `dotnet test --logger:"junit"` I get this warning in the output:

```
Starting test execution, please wait...
JunitXML Logger: The provided configuration item 'TargetFramework' is not valid and will be ignored. Note, names are case sensitive.
```

using dotnet 3.1.402

**Comment by Siphonophora** [comment]
@moly Hi. We are alerting on any command line args that are not defined / expected by this logger. `TargetFramework` must be coming from the test runner. So, its safe to ignore. 

We are looking at changing how these args are handled, so this may be removed in the future.

**Comment by gitfool** [comment]
Meanwhile, this should actually be expected by the logger, so it should be added to the list of [known keys](https://github.com/spekt/junit.testlogger/blob/bf1649ea44300c02c69627a6a97d10b02590caea/src/JUnit.Xml.TestLogger/JUnitXmlTestLogger.cs#L181).

Commands observed with Sysinternals [Process Monitor](https://docs.microsoft.com/en-us/sysinternals/downloads/procmon):
```
"C:/Program Files/dotnet/dotnet.exe" test "D:/Devel/Repos/TestService/Tests/Tests.csproj" --logger "console;verbosity=detailed" --configuration Release --no-build --no-restore --results-directory "D:/Devel/Repos/TestService/Artifacts/Tests/Tests" --logger "junit"

"dotnet.exe" exec "C:\Program Files\dotnet\sdk\5.0.100\MSBuild.dll" -maxcpucount -verbosity:m -target:VSTest -nodereuse:false -nologo -property:VSTestLogger=\"console%3bverbosity=detailed;junit\" -property:Configuration=Release -property:VSTestNoBuild=true -property:VSTestResultsDirectory=D:\Devel\Repos\TestService\Artifacts\Tests\Tests D:/Devel/Repos/TestService/Tests/Tests.csproj

"dotnet" exec "C:\Program Files\dotnet\sdk\5.0.100\vstest.console.dll" --settings:D:\Devel\Repos\TestService\Tests/Tests.runsettings --testAdapterPath:C:\Users\sfausett\.nuget\packages\coverlet.collector\1.3.1-preview.27.gdd2237a3be\build\netstandard1.0\ --framework:.NETCoreApp,Version=v5.0 --logger:console;verbosity=detailed --logger:junit --resultsDirectory:D:\Devel\Repos\TestService\Artifacts\Tests\Tests D:\Devel\Repos\TestService\Tests\bin\Release\Tests.dll --testAdapterPath:C:\Users\sfausett\.nuget\packages\microsoft.codecoverage\16.8.0\build\netstandard1.0\
```
Confirmed by looking at the [VSTest](https://github.com/microsoft/vstest) internals, the default logger parameters always include `TargetFramework`:
* [TestLoggerManager.UpdateLoggerParameters](https://github.com/microsoft/vstest/blob/5354492943722ee83de2a82574411e87289730b7/src/Microsoft.TestPlatform.CrossPlatEngine/Client/TestLoggerManager.cs#L650)
* [Constants.DefaultLoggerParameterNames](https://github.com/microsoft/vstest/blob/5354492943722ee83de2a82574411e87289730b7/src/Microsoft.TestPlatform.ObjectModel/Constants.cs#L244)

**Comment by Siphonophora** [comment]
@gitfool @moly @alexpizarroj Apologies for the delay, work has been crazy. I'm happy to get rid of this warning for now. The pre-release version is here. https://www.myget.org/feed/spekt/package/nuget/JunitXml.TestLogger/2.1.81

@codito I tested this and it resolves the nuisance warning. Could you cut a release when you have a minute?

**Comment by codito** [comment]
Wish you all a very happy new year! Just pushed `2.1.81` to nuget. @Siphonophora we can now create a github release with changelog.

**Comment by Siphonophora** [comment]
Thanks @codito. Happy New year!

The release notes are done. Thanks again everyone.
