### ISSUE TITLE
Need test name to include parameter for Theory test case

### ISSUE THREAD

**Issue by chaintng** [spekt/junit.testlogger#53]
![image](https://user-images.githubusercontent.com/2979072/167865136-003c316b-57e3-4e81-a5b7-712815e5d39a.png)

C# support `Theory` test case
https://docs.microsoft.com/en-us/dotnet/core/testing/unit-testing-with-dotnet-test#add-more-tests

That has parameter in the test function

This should include in the test name
Otherwise, it will show the same test case for all parameter

I tried to look into the code, but i'm not sure do we have this value in `TestResultInfo` class yes

If yes, please help advise, i can help contribute

Thank you so much.

**Comment by Siphonophora** [comment]
@chaintng Hi. This is actually going to be in our next release. You can use the feature in the preview package on our MyGet feed. https://www.myget.org/feed/spekt/package/nuget/JunitXml.TestLogger

**Comment by chaintng** [comment]
@Siphonophora how can i see the source code? Could you please advise which parameter should i gave to get this output ?

**Comment by Siphonophora** [comment]
Most of the source is in another repo. You are probably interested in this file: https://github.com/spekt/testlogger/blob/master/src/TestLogger/Extensions/XunitTestAdapter.cs

The theory data should be there by default now, with the version in MyGet. If that isn't working, please provide an example I can look at.

**Comment by Siphonophora** [comment]
@chaintng Actually, we just released that package to nuget, so you don't need to get it from MyGet.
