### ISSUE TITLE
Release v3.0.114

### ISSUE THREAD

**Issue by mark-monteiro** [spekt/junit.testlogger#54]
A new release has been published on NuGet with version v3.0.114, but there has been no associated release in GitHub or release notes added anywhere. There is also no tag for this version added to the repository to indicate what commits are included in the release.

Without a proper release being performed, it is not possible to update to the latest version of the package confidently.

**Comment by Siphonophora** [comment]
@mark-monteiro Thanks. I totally forgot. Added the release.
