### ISSUE TITLE
Release v3.0.125

### ISSUE THREAD

**Issue by DerMolly** [spekt/junit.testlogger#67]
Apparently the same thing happened again as it did with https://github.com/spekt/junit.testlogger/issues/54

Maybe it would be benefical to include a release checklist in the repo to mitgate this problem in the future?

**Comment by codito** [comment]
@DerMolly is it possible for you quickly try this Pre release package if it fixes the issue? https://www.myget.org/feed/spekt/package/nuget/JunitXml.TestLogger/3.0.134

**Comment by codito** [comment]
I can cut a release based on feedback. /cc:@siphonophora

**Comment by DerMolly** [comment]
@codito The problem was about not having a release or tag on GitHub. I'm not sure what I should test? It seems to me (and I may be wrong) that both `3.0.125` and `3.0.134` are not present in this repo (neither as tags or as releases).
![grafik](https://github.com/spekt/junit.testlogger/assets/3978662/48ec57e5-c722-4fb1-ae85-5f8f6f28a9a6)
![grafik](https://github.com/spekt/junit.testlogger/assets/3978662/8bf77c9e-110e-420d-bb4e-e9f229b8d0c7)

**Comment by codito** [comment]
@DerMolly the link I shared is for a pre-release package (`3.0.134`). We use a myget feed for unreleased packages, tags are created for the nuget packages.

We can test pre-release package like this:

```
> cd <path of the test project using junit logger> # or create a new test project with `dotnet new`
> dotnet add package JunitXml.TestLogger --version 3.0.134 --source https://www.myget.org/F/spekt/api/v3/index.json
# add the failing test
> dotnet test --logger:junit
```

`3.0.125` is a release package and should have a tag and release notes. We will create it.

**Comment by DerMolly** [comment]
I don't have any problems with the package what so ever. I only noticed while renovate suggested my to update this package that there are no releases and therefore no release notes to gather if I need to change anything. I mean it's a patch release so I would not suspect as much, but I try to always have a quick look anyway.
If this will be added I thank you very much.

**Comment by codito** [comment]
@DerMolly we have unlisted `3.0.125`, it was missing the intended fix. Latest release is https://github.com/spekt/junit.testlogger/releases/tag/v3.0.134 and https://www.nuget.org/packages/JunitXml.TestLogger/3.0.134.

Closing this issue. Thanks again for the feedback!
