### ISSUE TITLE
JUnit results file missing on MacOS when code coverage collector is used

### ISSUE THREAD

**Issue by ablok** [spekt/junit.testlogger#72]
When running a dotnet test command using `--logger "jUnit"`, a  `TestResults.xml` file will be created. However, when adding the `--collect "Code Coverage"` option, the `TestResults.xml` file will no longer be created. This happes on MacOS. On Windows the file will be created as expected.

I created a sample project here: https://github.com/ablok/JunitLoggerExample

**Comment by codito** [comment]
@ablok I don't have access to a MacOS box. I can validate that TestResults.xml is created on Linux.

Would it be possible to share a trace log? https://github.com/microsoft/vstest/blob/main/docs/diagnose.md#collect-traces-using-command-line

**Comment by ablok** [comment]
@codito here is the output from the `dotnet test` command while adding the `--diag:log.txt` option.

[log.datacollector.24-02-09_13-09-43_24858_5.txt](https://github.com/spekt/junit.testlogger/files/14221591/log.datacollector.24-02-09_13-09-43_24858_5.txt)
[log.host.24-02-09_13-09-44_80011_5.txt](https://github.com/spekt/junit.testlogger/files/14221592/log.host.24-02-09_13-09-44_80011_5.txt)
[log.txt](https://github.com/spekt/junit.testlogger/files/14221593/log.txt)

**Comment by codito** [comment]
Thanks @ablok, the logs helped! I think we need to apply a fix to exclude all Spekt* assemblies from code coverage, the Code Coverage instrumentation is messing up test result callbacks and hence we never get a call back to save the run results.

**Workaround**
[test.runsettings.txt](https://github.com/spekt/junit.testlogger/files/14222490/test.runsettings.txt)

- Copy above file as `test.runsettings`
- Try this command:
`dotnet test Example.sln --results-directory "./output" --logger "jUnit" --collect "Code Coverage" --settings test.runsettings`

**Comment by ablok** [comment]
@codito the workaround indeed works.

**Comment by codito** [comment]
Fix released with https://www.nuget.org/packages/JunitXml.TestLogger/3.1.12
