### ISSUE TITLE
Change testsuite name property in JUnit xml

### ISSUE THREAD

**Issue by venka66** [spekt/junit.testlogger#78]
I'm using `dotnet test` with the `junit` logger option to run my tests. The tests are compiled into a binary before they are run and the name of the binary is used as the `testsuite name` in the JUnit XML file, example - `E2ETests.dll`. 

```
<testsuites>
<testsuite name="E2ETests.dll" tests="5" skipped="1" failures="2" errors="0" time="76.0077336" timestamp="2024-04-11T16:31:15" hostname="hostname" id="0" package="E2ETests.dll">
```

I would like to change the name of the testsuite in the XML file without modifying the binary. Is there an existing method or plan to allow changing the `testsuite name` that can be provided to `dotnet test --logger` option?

**Comment by codito** [comment]
@venka66 we don't plan to add this support, please consider using a post processing task with Powershell or similar scripting for this.
